// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ExtraLink: typeof import('./components/ExtraLink.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GitbookLink: typeof import('./components/GitbookLink.vue')['default']
    Hello: typeof import('./components/Hello.vue')['default']
    ListPosts: typeof import('./components/ListPosts.vue')['default']
    ListProjects: typeof import('./components/ListProjects.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
    ToggleTheme: typeof import('./components/ToggleTheme.vue')['default']
    ToggleTheme2: typeof import('./components/ToggleTheme2.vue')['default']
  }
}

export { }
